spring.application.name=modelocarro
server.port=8080
springdoc.swagger-ui.path=/
api.version=v1

spring.datasource.url=jdbc:mysql://localhost:3306/modelocarro?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root_pwd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
