spring.application.name=modelocarro
server.port=8080

springdoc.swagger-ui.path=/
api.version=v1

# Database - SQL Server
# Quando a API está em um container e o SQL Server está no host,
# use host.docker.internal como DB_SERVER_URL.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=api;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1q2w3e4R@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect